commit 28c44c554c9aca6e39c53f4ab942eac657daf654
Author: Simon Li <orpheus+devel@gmail.com>
Date:   Fri Aug 21 17:55:28 2015 +0100

    Don't fail in check_mode if user exists
    
    PR #1651 fixed issue #1515 but the requirement for path to be defined is unecessarily strict. If the user has previously been created a path isn't necessary.

diff --git a/lib/ansible/modules/system/authorized_key.py b/lib/ansible/modules/system/authorized_key.py
index f9f773d8d9..376cf4c61d 100644
--- a/lib/ansible/modules/system/authorized_key.py
+++ b/lib/ansible/modules/system/authorized_key.py
@@ -169,16 +169,15 @@ def keyfile(module, user, write=False, path=None, manage_dir=True):
     :return: full path string to authorized_keys for user
     """
 
-    if module.check_mode:
-        if path is None:
-            module.fail_json(msg="You must provide full path to key file in check mode")
-        else:
-            keysfile = path
-            return keysfile
+    if module.check_mode and path is not None:
+        keysfile = path
+        return keysfile
 
     try:
         user_entry = pwd.getpwnam(user)
     except KeyError, e:
+        if module.check_mode and path is None:
+            module.fail_json(msg="Either user must exist or you must provide full path to key file in check mode")
         module.fail_json(msg="Failed to lookup user %s: %s" % (user, str(e)))
     if path is None:
         homedir    = user_entry.pw_dir
