commit 6d680d82819d35c1ce6444ca4c64612eb5d09f30
Author: joren485 <jorenvrancken@gmail.com>
Date:   Wed Aug 1 16:24:31 2018 +0200

    Use socket.error instead of non-existent socket.Error (#43499)

diff --git a/lib/ansible/module_utils/network/cnos/cnos.py b/lib/ansible/module_utils/network/cnos/cnos.py
index ac737c19fd..bd9d571c83 100644
--- a/lib/ansible/module_utils/network/cnos/cnos.py
+++ b/lib/ansible/module_utils/network/cnos/cnos.py
@@ -3580,7 +3580,7 @@ def validateValueAgainstRule(ruleString, variableValue):
         try:
             socket.inet_pton(socket.AF_INET, variableValue)
             result = True
-        except socket.Error:
+        except socket.error:
             result = False
         if(result is True):
             return "ok"
@@ -3598,7 +3598,7 @@ def validateValueAgainstRule(ruleString, variableValue):
                 result = True
             else:
                 result = False
-        except socket.Error:
+        except socket.error:
             result = False
         if(result is True):
             return "ok"
@@ -3609,7 +3609,7 @@ def validateValueAgainstRule(ruleString, variableValue):
         try:
             socket.inet_pton(socket.AF_INET6, variableValue)
             result = True
-        except socket.Error:
+        except socket.error:
             result = False
         if(result is True):
             return "ok"
