commit 8ce627d9a2770967c0c51195804920fb04bdbd01
Author: Toshio Kuratomi <a.badger@gmail.com>
Date:   Fri Jun 3 06:25:29 2016 -0700

    Only import get_exception once in locale_gen.py

diff --git a/lib/ansible/modules/extras/system/locale_gen.py b/lib/ansible/modules/extras/system/locale_gen.py
index 48cfb3ed8b..7dbb9d5e96 100644
--- a/lib/ansible/modules/extras/system/locale_gen.py
+++ b/lib/ansible/modules/extras/system/locale_gen.py
@@ -15,11 +15,6 @@
 #
 # You should have received a copy of the GNU General Public License
 # along with Ansible.  If not, see <http://www.gnu.org/licenses/>.
-import os
-import os.path
-from subprocess import Popen, PIPE, call
-import re
-from ansible.module_utils.pycompat24 import get_exception
 
 DOCUMENTATION = '''
 ---
@@ -48,6 +43,14 @@ EXAMPLES = '''
 - locale_gen: name=de_CH.UTF-8 state=present
 '''
 
+import os
+import os.path
+from subprocess import Popen, PIPE, call
+import re
+
+from ansible.module_utils.basic import *
+from ansible.module_utils.pycompat24 import get_exception
+
 LOCALE_NORMALIZATION = {
     ".utf8": ".UTF-8",
     ".eucjp": ".EUC-JP",
@@ -65,9 +68,6 @@ LOCALE_NORMALIZATION = {
 # location module specific support methods.
 #
 
-from ansible.module_utils.basic import *
-from ansible.module_utils.pycompat24 import get_exception
-
 def is_available(name, ubuntuMode):
     """Check if the given locale is available on the system. This is done by
     checking either :
