commit b154ad4cbb20f6b258f2afd3e0985101b7f0868b
Author: Hagai Kariti <hkariti@gmail.com>
Date:   Thu Jun 4 11:41:02 2015 +0300

    ec2_vol: fix race conditions because we handle errors before actually deleting
    
    Just try to delete the volume and handle the error amazon sends

diff --git a/lib/ansible/modules/cloud/amazon/ec2_vol.py b/lib/ansible/modules/cloud/amazon/ec2_vol.py
index 3065b55045..d5b4dd4f3b 100644
--- a/lib/ansible/modules/cloud/amazon/ec2_vol.py
+++ b/lib/ansible/modules/cloud/amazon/ec2_vol.py
@@ -239,15 +239,14 @@ def get_volumes(module, ec2):
     return vols
 
 def delete_volume(module, ec2):
-    vol = get_volume(module, ec2)
-    if not vol:
-        module.exit_json(changed=False)
-    else:
-       if vol.attachment_state() is not None: 
-           adata = vol.attach_data
-           module.fail_json(msg="Volume %s is attached to an instance %s." % (vol.id, adata.instance_id))
-       ec2.delete_volume(vol.id)
-       module.exit_json(changed=True)
+    volume_id = module.params['id']
+    try:
+        ec2.delete_volume(volume_id)
+        module.exit_json(changed=True)
+    except boto.exception.EC2ResponseError as ec2_error:
+        if ec2_error.code == 'InvalidVolume.NotFound':
+            module.exit_json(changed=False)
+        module.fail_json(msg=ec2_error.message)
 
 def boto_supports_volume_encryption():
     """
