commit 0329d96fb8b130a40009a396b2367e2129d333cc
Author: Loïc Estève <loic.esteve@ymail.com>
Date:   Tue Feb 5 23:44:14 2013 +0000

    BUG: Creating DatetimeIndex from empty array with datetime64 dtype raises IndexError

diff --git a/pandas/tests/test_common.py b/pandas/tests/test_common.py
index e9f19e0fb..b3a0c5ee9 100644
--- a/pandas/tests/test_common.py
+++ b/pandas/tests/test_common.py
@@ -106,6 +106,10 @@ def test_isnull_datetime():
     assert(mask[0])
     assert(not mask[1:].any())
 
+def test_datetimeindex_from_empty_datetime64_array():
+    for unit in [ 'ms', 'us', 'ns' ]:
+        idx = DatetimeIndex(np.array([], dtype='datetime64[%s]' % unit))
+        assert(len(idx) == 0)
 
 def test_any_none():
     assert(com._any_none(1, 2, 3, None))
diff --git a/pandas/tseries/index.py b/pandas/tseries/index.py
index cf9c77f0c..823b24631 100644
--- a/pandas/tseries/index.py
+++ b/pandas/tseries/index.py
@@ -228,7 +228,7 @@ class DatetimeIndex(Int64Index):
                     offset = data.offset
                     verify_integrity = False
             else:
-                if data.dtype != _NS_DTYPE:
+                if data.dtype != _NS_DTYPE and data.size:
                     subarr = tslib.cast_to_nanoseconds(data)
                 else:
                     subarr = data
